### ISSUE TITLE
Error on importing netfilterqueue in python3

### ISSUE THREAD

**Issue by PidgeyL** [jlaine/python-netfilter#1]
When I open python3 (with super user privileges) and type `from netfilterqueue import NetfilterQueue
`, I'm getting the following ImportError:
`ImportError: /usr/local/lib/python3.4/dist-packages/netfilterqueue.cpython-34m.so: undefined symbol: PyString_FromStringAndSize`
The same code works under python2, so I assumed, since this package is also available under python3, this would also work. Am I mistaken, or is this a bug? Or is the code different?

Thanks in advance

**Comment by jlaine** [comment]
The NetfilterQueue package is a different project:

https://github.com/kti/python-netfilterqueue
