### ISSUE TITLE
ERROR: It seems that you are offline. Please check your internet connection when running

### ISSUE THREAD

**Issue by Developer103** [jlaine/python-netfilter#3]
After I installed the requirements using the code in README.md, i did `sudo python3 kickthemout.py`.  When I did that, this message: `ERROR: It seems that you are offline. Please check your internet connection` popped up, and I wasn't able to run the program. Please help.

**Comment by jlaine** [comment]
This error is fired by kickmeout, not python-netfilter:

https://github.com/k4m4/kickthemout/blob/9238b1bd88a25bd0709a195e599037f1acca9551/kickthemout.py#L746
